# Generated by Django 3.2 on 2021-10-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='name',
        ),
    ]
